### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'CLOSED'

### ISSUE THREAD

**Issue by leoobrabo** [nsiregar/shpee#2]
Hello, I saw your code, and I saw that it does exactly what I need, congratulations, because it is the only one on the internet!

The problem is that now it's giving an error and I can't fix it, I hope it's easy for you

Thanks in advance

Error

Exception ignored in: <function Client.__del__ at 0x000001E3823FBD30>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 1281, in __del__
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 1242, in close
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_transports\default.py", line 216, in close
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\connection_pool.py", line 307, in close
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 159, in close
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\http11.py", line 211, in close
AttributeError: 'NoneType' object has no attribute 'CLOSED'

**Comment by nsiregar** [comment]
can you share your snippet code? I was unable to repro this issue
